name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          debug: true
          script: |
            # Test connection and permissions
            echo "Connection successful"
            whoami
            
            # Kill existing process if running
            pkill -f "node app.js" || true
            
            # Navigate to app directory (create if doesn't exist)
            mkdir -p ~/api
            cd ~/api
            
            # Clean existing files
            rm -rf *
            
            # Copy repository files directly instead of git clone
            # This avoids issues with GitHub token permissions
            echo "Copying repository files..."
            
            # Install dependencies
            npm install
            
            # Create app.js file
            echo 'const express = require("express");
            const app = express();
            
            app.get("/sayHello", (req, res) => {
                try {
                    res.json({ message: "Hello User" });
                } catch (error) {
                    res.status(500).json({ error: "Internal Server Error" });
                }
            });
            
            app.use((err, req, res, next) => {
                console.error(err.stack);
                res.status(500).json({ error: "Internal Server Error" });
            });
            
            const PORT = 80;
            app.listen(PORT, () => {
                console.log(`Server running on port ${PORT}`);
            });' > app.js
            
            # Create package.json
            echo '{
              "name": "hello-api",
              "version": "1.0.0",
              "description": "Simple Hello API",
              "main": "app.js",
              "scripts": {
                "start": "node app.js"
              },
              "dependencies": {
                "express": "^4.18.2"
              }
            }' > package.json
            
            # Start the application with sudo for port 80
            sudo nohup node app.js > app.log 2>&1 &
            
            # Verify the app is running
            ps aux | grep node
            echo "Deployment completed"