name: Deploy API

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            # Install Node.js if not present
            if ! command -v node > /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Kill existing process if running
            sudo pkill -f "node app.js" || true

            # Prepare app directory
            mkdir -p ~/hellouser
            cd ~/hellouser

            # Clean old files
            rm -rf *

            # Clone repo (private, use token)
            git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} . || git pull

            # Install dependencies
            npm install

            # Start app on port 80 with sudo and nohup
            sudo nohup node app.js > app.log 2>&1 &